steps:
- name: 'bash'
  entrypoint: 'bash'
  args: ['-c', 'echo let us assume there are tests here']
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/markdown-to-docs/markdown-to-docs:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/markdown-to-docs/markdown-to-docs:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'markdown-to-docs', '--image', 'gcr.io/markdown-to-docs/markdown-to-docs:latest', '--region', 'europe-west1', '--platform', 'managed']
images:
- gcr.io/markdown-to-docs/markdown-to-docs:latest
timeout: '1600s'